# Generated by Django 5.0 on 2023-12-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('current_job_place', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('year_of_experience', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('website_link', models.URLField()),
                ('language', models.CharField(max_length=255)),
                ('career_objective', models.TextField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('pinterest', models.URLField()),
                ('dribbble', models.URLField()),
                ('behance', models.URLField()),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=20)),
                ('present_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('education_level', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('result_gpa', models.CharField(max_length=10)),
                ('starting_period_education', models.DateField()),
                ('ending_period_education', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('designation_employment', models.CharField(max_length=255)),
                ('starting_period_employment', models.DateField()),
                ('ending_period_employment', models.DateField()),
                ('continuing_working_here', models.BooleanField(default=False)),
                ('responsibility', models.TextField()),
            ],
        ),
    ]
