# Generated by Django 5.0 on 2023-12-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='continuing_working_here',
        ),
    ]
