# Generated by Django 5.0 on 2023-12-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_remove_userprofile_continuing_working_here'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
