# Generated by Django 4.2.4 on 2024-01-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_category', models.CharField(max_length=255)),
                ('vacancies', models.IntegerField()),
                ('salary_type', models.CharField(choices=[('fixedPrice', 'Fixed Salary'), ('rangePrice', 'Salary Range'), ('negotiable', 'Negotiable')], max_length=20)),
                ('job_fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_range_price_one', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_range_price_two', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_type', models.CharField(max_length=255)),
                ('experience_level', models.CharField(max_length=255)),
                ('job_tag', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('job_description', models.TextField()),
                ('job_image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
            ],
        ),
    ]
