# Generated by Django 4.2.4 on 2024-01-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_fixed_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_range_price_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_range_price_two',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
