# Generated by Django 4.2.4 on 2024-01-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_job_job_fixed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('fixedSalary', 'Fixed Salary'), ('hourlyWage', 'Hourly Wage'), ('projectBased', 'Project Based')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
